name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to test'
        required: true
        default: 'https://git-scm.com'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install @playwright/test
      run: npm install @playwright/test
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_TEST_URL: ${{ github.event.inputs.url }}
      run: npx playwright test --project=chrome
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
